### ISSUE TITLE
Updating Security Measures

### ISSUE THREAD

**Issue by singhaditya28** [google-research/lag#4]
Dear @david-berthelot ,
Hope you're doing well 😄 !

I found out this project and immediately realised its potential. I want to update the project with some secure syntax. Can I get the names of the**Python files** which are standalone and not being imported to other files so that I can create a dedicated PR ? Thanks in advance 👍 

PS :: I will try my best to make this project a success.

**Comment by david-berthelot** [comment]
This is not a project meant for collaboration, this is a snapshot of the source code associated with the LAG paper. Basically it is a reference, if you want to improve it or add modifications to it, I suggest that you fork it. Thanks.

**Comment by singhaditya28** [comment]
So, for creating a dedicated PR can I have the list to make the PR more recently available.  😃

**Comment by david-berthelot** [comment]
Sorry I don't have the information you are asking readily available. I'm not sure what you are trying to do but could probably grep the imports or something like that. Typically research code is open sourced so that people can ask technical questions related to the method itself. Here it seems you're trying to customize the code and it's outside of  the scope of what we can feasibly support. Thanks for your understanding.

**Comment by singhaditya28** [comment]
No worries, I'm not grep-ing the imports. I'm refactoring the code with the currently securest syntax which resolves some runtime errors and some security vulnerabilities.
So, can I work on that ?

**Comment by david-berthelot** [comment]
I think the best option in this case is to make your own fork in your own repo with all the changes you desire to make. This code is provided as-is as a way of reproducing results from the paper, it won't be updated, sorry to repeat myself but it's just a snapshot.
