### ISSUE TITLE
Critic inputs

### ISSUE THREAD

**Issue by Medabid1** [google-research/lag#8]
Hello, i have a question about the paper

![image](https://user-images.githubusercontent.com/30070233/87211539-f6149780-c2e7-11ea-8ac8-047485d09851.png)

Doesn't this allow the critic to spot the real samples by looking at the 0 ? 
This would make its job too easy and it will become too powerful for the generator, especially in the beginning, thus the generator won t be able to keep up.

**Comment by david-berthelot** [comment]
No it's the opposite, real samples are not continuous since originally they come from [0, 255]. Fake samples are continuous, so we round them before feeding into the critic to make them discontinous, e.g. `nearest(r*H(...))/r`.

**Comment by Medabid1** [comment]
I see, Thanks for the response,  So you round not just the difference `|y - round(r H(x))|/r` but also the x_z ?

**Comment by david-berthelot** [comment]
Sorry for the confusion, we only do it for the difference (the code is the ultimate reference since that's what produces the results from the paper):
https://github.com/google-research/lag/blob/master/lag.py#L147

But on second thought maybe it could be a good idea to do it also for the input of the critic (as an experiment).

**Comment by Medabid1** [comment]
it s okay, Thank you for your clarification. I'm re implementing the paper in pytorch, maybe i ll try it and see the results.
